function [fitresult, gof] = getRationalCurve(pvDistances, corrList)
%CREATEFIT(PVDISTANCES,CORRLIST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : pvDistances
%      Y Output: corrList
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Nov-2015 21:43:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( pvDistances, corrList );

% Set up fittype and options.
ft = fittype( 'rat11' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.942050590775485 0.956134540229802 0.575208595078466];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'corrList vs. pvDistances', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel pvDistances
% ylabel corrList
% grid on


