function [VarName1,AmbienttemperatureC,ACinverterpowerW,Angleofincidencedeg,BeamirradianceWm2,DCarraypowerW,DiffuseirradianceWm2,GlobalhorizontalirradianceWm2,ModuletemperatureC,PlaneofarrayirradianceWm2,PowergeneratedbysystemkW,Shadingfactorforbeamradiation,Sunupoverhorizon01,TransmittedplaneofarrayirradianceWm2,Windspeedms] = importSAMSolar(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME1,AMBIENTTEMPERATUREC,ACINVERTERPOWERW,ANGLEOFINCIDENCEDEG,BEAMIRRADIANCEWM2,DCARRAYPOWERW,DIFFUSEIRRADIANCEWM2,GLOBALHORIZONTALIRRADIANCEWM2,MODULETEMPERATUREC,PLANEOFARRAYIRRADIANCEWM2,POWERGENERATEDBYSYSTEMKW,SHADINGFACTORFORBEAMRADIATION,SUNUPOVERHORIZON01,TRANSMITTEDPLANEOFARRAYIRRADIANCEWM2,WINDSPEEDMS]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [VARNAME1,AMBIENTTEMPERATUREC,ACINVERTERPOWERW,ANGLEOFINCIDENCEDEG,BEAMIRRADIANCEWM2,DCARRAYPOWERW,DIFFUSEIRRADIANCEWM2,GLOBALHORIZONTALIRRADIANCEWM2,MODULETEMPERATUREC,PLANEOFARRAYIRRADIANCEWM2,POWERGENERATEDBYSYSTEMKW,SHADINGFACTORFORBEAMRADIATION,SUNUPOVERHORIZON01,TRANSMITTEDPLANEOFARRAYIRRADIANCEWM2,WINDSPEEDMS]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,AmbienttemperatureC,ACinverterpowerW,Angleofincidencedeg,BeamirradianceWm2,DCarraypowerW,DiffuseirradianceWm2,GlobalhorizontalirradianceWm2,ModuletemperatureC,PlaneofarrayirradianceWm2,PowergeneratedbysystemkW,Shadingfactorforbeamradiation,Sunupoverhorizon01,TransmittedplaneofarrayirradianceWm2,Windspeedms] = importfile('AL_34.65_-86.783.csv',2, 8761);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/05/17 22:19:27

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
AmbienttemperatureC = dataArray{:, 2};
ACinverterpowerW = dataArray{:, 3};
Angleofincidencedeg = dataArray{:, 4};
BeamirradianceWm2 = dataArray{:, 5};
DCarraypowerW = dataArray{:, 6};
DiffuseirradianceWm2 = dataArray{:, 7};
GlobalhorizontalirradianceWm2 = dataArray{:, 8};
ModuletemperatureC = dataArray{:, 9};
PlaneofarrayirradianceWm2 = dataArray{:, 10};
PowergeneratedbysystemkW = dataArray{:, 11};
Shadingfactorforbeamradiation = dataArray{:, 12};
Sunupoverhorizon01 = dataArray{:, 13};
TransmittedplaneofarrayirradianceWm2 = dataArray{:, 14};
Windspeedms = dataArray{:, 15};


