%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\NhatTan\Google Drive\shared\google_dc\NREL_SAM\AL_34.65_-86.783.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/10/15 16:55:22

%% Initialize variables.
filename = 'C:\Users\NhatTan\Google Drive\shared\google_dc\NREL_SAM\AL_34.65_-86.783.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
AmbienttemperatureC = dataArray{:, 2};
ACinverterpowerW = dataArray{:, 3};
Angleofincidencedeg = dataArray{:, 4};
BeamirradianceWm2 = dataArray{:, 5};
DCarraypowerW = dataArray{:, 6};
DiffuseirradianceWm2 = dataArray{:, 7};
GlobalhorizontalirradianceWm2 = dataArray{:, 8};
ModuletemperatureC = dataArray{:, 9};
PlaneofarrayirradianceWm2 = dataArray{:, 10};
PowergeneratedbysystemkW = dataArray{:, 11};
Shadingfactorforbeamradiation = dataArray{:, 12};
Sunupoverhorizon01 = dataArray{:, 13};
TransmittedplaneofarrayirradianceWm2 = dataArray{:, 14};
Windspeedms = dataArray{:, 15};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;